# Multi-variable Linear Regression

In [16]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.1.0


## Train Data
Predicting exam score - regression using three inputs (x1, x2, x3)

x1 (quiz 1) | x2 (quiz 2) | x3 (mid 1) | Y (final)
---- | ---- | ----| ----
73 | 80 | 75 | 152
93 | 88 | 93 | 185
89 | 91 | 90 | 180
96 | 98 | 100 | 196
73 | 66 | 70 | 142


In [17]:
data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
X = data[:, :-1] # 5행 3열
y = data[:, [-1]] # 5행 1열(마지막 열)

## Step 1: Hypothesis using matrix(가설 or 모델)
### Many x instances

$$ \begin{pmatrix} x_{ 11 } & x_{ 12 } & x_{ 13 } \\ x_{ 21 } & x_{ 22 } & x_{ 23 } \\ x_{ 31 } & x_{ 32 } & x_{ 33 }\\ x_{ 41 } & x_{ 42 } & x_{ 43 }\\ x_{ 51 } & x_{ 52 } & x_{ 53 }\end{pmatrix} \cdot \begin{pmatrix} w_{ 1 } \\ w_{ 2 } \\ w_{ 3 } \end{pmatrix} + b=\begin{pmatrix} x_{ 11 }w_{ 1 }+x_{ 12 }w_{ 2 }+x_{ 13 }w_{ 3 } \\ x_{ 21 }w_{ 1 }+x_{ 22 }w_{ 2 }+x_{ 23 }w_{ 3 }\\ x_{ 31 }w_{ 1 }+x_{ 32 }w_{ 2 }+x_{ 33 }w_{ 3 } \\ x_{ 41 }w_{ 1 }+x_{ 42 }w_{ 2 }+x_{ 43 }w_{ 3 } \\ x_{ 51 }w_{ 1 }+x_{ 52 }w_{ 2 }+x_{ 53 }w_{ 3 } \end{pmatrix} + b$$

$$ [5, 3] \cdot [3, 1] = [5, 1] $$

$$ H(X) = XW + b$$

In [18]:
tf.random.set_seed(0)  # for reproducibility

# 임의의 값으로 변수 설정
W = tf.Variable(tf.random.normal((3, 1))) # 3행 1열
b = tf.Variable(tf.random.normal((1,)))

# 가설
# hypothesis, prediction function
def predict(X):
    return tf.matmul(X, W) + b

## Step 2: Cost Function (손실 함수)
$$ cost(W, b)=\frac { 1 }{ m } \sum _{i=1}^{m}{ { (H{ x }^{ i }-y^{ i } })^{ 2 } }  $$

In [19]:
# tf.reduce_mean(): 평균
# tf.square(a): a^2
cost = tf.reduce_mean((tf.square(predict(X) - y)))

## Step 3: Optimizer (Minimize Cost Function)
### Gradient descent
$$ W := W-\alpha \frac { \partial  }{ \partial W } cost(W) $$

In [20]:
# 경사 하강법
# tf.GradientTape() 사용
learning_rate = 0.000001

## 훈련

In [21]:
# 훈련 반복 횟수 설정
epoch = 2000
for i in range(epoch + 1):
    # Gradient descent (경사하강법)
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))
        
    # 경사하강법으로 w, b의 기울기 값(미분)을 얻는다.
    # calculates the gradients of the loss
    W_grad, b_grad = tape.gradient(cost, [W, b])
    
    # w, b의 값을 업데이트
    # a.assign_sub(b): a = a - b
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    # 100번에 한번 값 출력
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

    0 |  1798.2894
  100 |     2.2888
  200 |     2.0632
  300 |     2.0587
  400 |     2.0542
  500 |     2.0498
  600 |     2.0453
  700 |     2.0409
  800 |     2.0366
  900 |     2.0322
 1000 |     2.0279
 1100 |     2.0236
 1200 |     2.0194
 1300 |     2.0151
 1400 |     2.0108
 1500 |     2.0066
 1600 |     2.0024
 1700 |     1.9982
 1800 |     1.9940
 1900 |     1.9899
 2000 |     1.9857


## Predict (예측)

In [22]:
y # labels, 실제값

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)

In [23]:
predict(X).numpy() # prediction, 예측값

array([[151.39648],
       [184.93794],
       [180.81708],
       [194.1263 ],
       [144.31987]], dtype=float32)

In [24]:
# 새로운 데이터에 대한 예측

predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy() 

array([[182.69525],
       [174.3433 ]], dtype=float32)